@baseUrl = http://localhost:3001

### Test 1: Convert number to roman number
POST {{baseUrl}}/roman/convert
Content-Type: application/json

{
  "number": 79
}

### Test 2: Error, number bigger than 100
POST {{baseUrl}}/roman/convert
Content-Type: application/json

{
  "number": 170
}